
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ssldata:/etc/nginx/certs
    networks:
      - shared

networks:
  shared:
    external: true
volumes:
  ssldata:
    external: true
    name: magento_ssldata